name: Debian 10 AMD64

on:
  push:
    paths:
      - "templates/debian-10-amd64.pkr.hcl"
    branches:
      - main

env:
  IMAGE_REGISTRY: ghcr.io
  IMAGE_DISTRIBUTION: groovecommunity
  IMAGE_NAME: packer
  IMAGE_TAGS: latest unstable

jobs:

  validate_packer_template:

      name: Validate Packer template
      runs-on: ubuntu-20.04
      
      steps:

        - name: Check out the reposiotry
          uses: actions/checkout@v2
          
        - name: Packer Validate
          id: packer_validate
          uses: docker://ghcr.io/groovecommunity/packer:unstable
          timeout-minutes: 10
          with:
            args: packer validate -syntax-only "templates/debian-10-amd64.pkr.hcl"

  build_ami:

      name: Build AMI from Packer template
      runs-on: ubuntu-20.04
      environment: unstable

      needs:
        - validate_packer_template
      
      steps:

        - name: Check out the reposiotry
          uses: actions/checkout@v2
          
        - name: Packer Build
          id: packer_build
          uses: docker://ghcr.io/groovecommunity/packer:unstable
          timeout-minutes: 30
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          with:
            args: packer build -color=false -on-error=abort "templates/debian-10-amd64.pkr.hcl"